### ISSUE TITLE
Client initiation should be validated before it is used

### ISSUE THREAD

**Issue by sam-heller** [WickrInc/wickrio_addon#5]
In example app client initiation is a single call with a response value that is not interrogated before used later in example
```
var response = addon.clientInit(client);
```
It is unclear from given boilerplate whether or not this client initiation has any potential latency in execution, but without utilizing promises or some other of async handling there is no way to be sure that the client has been initialized before the later example commands are executed.

**Comment by ronmshv** [comment]
Hi @sam-heller,

Thanks for bringing this to our attention, the code excerpt in the README file of wickrio_addon is outdated and will be corrected soon. However, the actual wickrio-example-app repo(https://github.com/WickrInc/wickrio-example-app) contains the correct way to get started with creating a Wickr Integration(will also be updated very soon). Also, watch out for the release of the WickrIO Bot API which will make creating Wickr bots/integrations easier all together.
